language: java
sudo: false
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: mvn clean verify
deploy:
  on:
    branch: master
  provider: heroku
  api_key: $HEROKU_KEY
  app: $HEROKU_APP
