language: java
jdk: openjdk16
sudo: true
services: postgresql
env:
  - DB_URL=jdbc:postgresql:travis_ci_test
  - DB_USER=postgres
  - DB_PASSWORD=
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
before_install:
  - chmod +x mvnw
deploy:
  on:
    branch: master
  provider: heroku
  api_key: $HEROKU_KEY
  app: $HEROKU_APP
cache:
  directories:
    - $HOME/.m2
