spring:
  datasource:
    url: ${DATABASE_URL}
  jpa:
    open-in-view: false
server:
  error:
    include-exception: true
    include-message: always
jwt:
  token:
    secret: ${JWT_SECRET}
    expires: 3600000