spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: on
    hibernate:
      ddl-auto: validate
server:
  error:
    include-exception: true
    include-message: always
    include-binding-errors: always
jwt:
  token:
    secret: "k4rnaj1ks-cafe"
    expires: 3600000