create table dishes
(
    id    bigint not null generated by default as identity ,
    name  character varying(255) unique ,
    price double precision,
    primary key (id)
);

CREATE TABLE drinks
(
    id    bigint NOT NULL generated by default as identity ,
    name  character varying(255),
    price double precision,
    primary key (id)
);

CREATE TABLE ingredients
(
    id   bigint NOT NULL generated by default as identity,
    name character varying(255) unique ,
    primary key (id)
);

CREATE TABLE users
(
    id         bigint NOT NULL generated by default as identity ,
    created_at timestamp without time zone,
    status     character varying(255),
    updated_at timestamp without time zone,
    email      character varying(255) unique ,
    first_name character varying(255),
    last_name  character varying(255),
    password   character varying(255),
    username   character varying(255),
    primary key (id)
);

CREATE TABLE orders
(
    id     bigint NOT NULL generated by default as identity ,
    status integer,
    user_id bigint references users(id),
    primary key (id)
);

create table dish_ingredients
(
    dish_id       bigint not null references dishes(id),
    ingredient_id bigint not null references ingredients(id)
);

create table dish_orders
(
    id      bigint not null generated by default as identity ,
    amount  bigint,
    dish_id bigint references dishes(id),
    primary key (id)
);



create table drink_orders
(
    id       bigint not null generated by default as identity,
    amount   bigint,
    drink_id bigint references drinks(id),
    primary key (id)
);


CREATE TABLE excluded_dish_ingredients
(
    dish_order_id bigint NOT NULL references dish_orders(id),
    ingredient_id bigint NOT NULL references ingredients(id)
);


CREATE TABLE orders_dishes
(
    order_id  bigint NOT NULL references orders(id),
    dishes_id bigint NOT NULL unique references dish_orders(id)
);

CREATE TABLE orders_drinks
(
    order_id  bigint NOT NULL references orders(id),
    drinks_id bigint NOT NULL unique references drink_orders(id)
);

CREATE TABLE roles
(
    id         bigint NOT NULL generated by default as identity ,
    created_at timestamp without time zone,
    status     character varying(255),
    updated_at timestamp without time zone,
    name       character varying(255),
    primary key (id)
);


CREATE TABLE user_roles
(
    user_id bigint NOT NULL references users(id),
    role_id bigint NOT NULL references roles(id)
);

COPY roles (id, created_at, status, updated_at, name) FROM stdin;
1	2021-08-28 20:43:35	ACTIVE	2021-08-28 20:43:41	ROLE_USER
2	2021-08-28 20:43:35	ACTIVE	2021-08-28 20:43:41	ROLE_ADMIN
3	2021-08-28 20:43:35	ACTIVE	2021-08-28 20:43:41	ROLE_COOK
\.

COPY users (id, created_at, status, updated_at, email, first_name, last_name, password, username) FROM stdin;
1	2021-08-28 20:44:56.942104	ACTIVE	2021-08-28 20:44:56.942104	test@email.com	\N	\N	$2a$10$3jHQnfbFomLLndXbfbyq3.Jim/teSU9.E1fRp/rl5XEmPK.lETn0e	k4rnaj1k
\.

COPY user_roles (user_id, role_id) FROM stdin;
1	1
1	2
1	3
\.

